#ifndef RESOURCES_H
#define RESOURCES_H

#define IDI_ICON1 101
#define IDR_MYMENU 102
#define ID_FILE_EXIT 40001
#define IDM_TOGGLE 40002
#define ID_HELP_ABOUT 40003
#define ID_TRAY_SHOW 1001
#define ID_TRAY_EXIT 1002

#define ID_GENERATE_BTN 1
#define ID_COPY_BTN 2
#define ID_LOWERCASE_CHK 3
#define ID_UPPERCASE_CHK 4
#define ID_DIGITS_CHK 5
#define ID_SYMBOLS_CHK 6
#define ID_LENGTH_EDIT 7
#define ID_PASSWORD_TEXT 8

#endif